### ISSUE TITLE
overlay size

### ISSUE THREAD

**Issue by billiemead** [thewhyse/elevartherapeutics.com#5]
[![Screenshot_2023-10-15_00-49-29.png](https://mrkr.io/s/652b37181fe896d7fceaa196/2)](https://mrkr.io/s/652b37181fe896d7fceaa196/0)

Billie, this overlay is so large that I cannot view the entire item on my desktop monitor - any way to reduce the overall size?

---

**Reported by:** Krissy Onore (konore@mjhassoc.com)

**Source URL:** [https://test-elevartherapeutics.pantheonsite.io/](https://test-elevartherapeutics.pantheonsite.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/652b37181fe896d7fceaa199_f32aac3ebaed547d?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/652b37181fe896d7fceaa199_f32aac3ebaed547d?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/652b37181fe896d7fceaa199_f32aac3ebaed547d?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/652b37181fe896d7fceaa199_f32aac3ebaed547d?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 11 (15.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>2844 x 1025</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by MasterMJH** [comment]
trying to drop screen shot here for your reference - this is on my laptop screen at 100% 
![overlay screenshot](https://github.com/thewhyse/elevartherapeutics.com/assets/48516602/b72b2449-86fd-47fe-b529-f7f32e556d03)

**Comment by billiemead** [comment]
Fixed for 2560px x 1080px viewport

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/652b37181fe896d7fceaa199_f32aac3ebaed547d) - This issue was marked as **✅ Resolved** in Marker.io
